### ISSUE TITLE
Exception override

### ISSUE THREAD

**Issue by teachop** [japaric/cortex-m-quickstart#2]
What would be the example syntax to replace a default exception now?  In particular SysTick.  It isn't a big problem as I switched to a Timx periodic interrupt for the time being.  Huge thanks to you for so much good useful work on Rust embedded!

**Comment by japaric** [comment]
I have added an example! :-)

**Comment by teachop** [comment]
Ah, it was disable the default feature I didn't catch.  Works fine, thanks.
