### ISSUE TITLE
Update to latest cortex-m?

### ISSUE THREAD

**Issue by thejpster** [japaric/cortex-m-quickstart#22]
I notice that `hprintln!` is missing from the later versions of the cortex-m crate. Is there a replacement?

**Comment by japaric** [comment]
> Is there a replacement?

`write!` macro from core + `hio::hstdout` from cortex-m-semihosting

**Comment by thejpster** [comment]
Ah. Will there be a new version of the quickstart at some point? I might be able to help, if I can find the time.

**Comment by jamesmunns** [comment]
Additionally, examples like [this one](https://github.com/japaric/cortex-m-rtfm/blob/master/examples/one-task.rs) will not work with the current `cortex-m` (relies on a component from 0.4.x)

**Comment by kitling** [comment]
Fixed as of v0.2.5?

**Comment by japaric** [comment]
@kitling yes, thanks for the heads up. Closing this issue then.
